// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAl9HZV3RgWfAh8Oe9Cg1CCG2WSKt93xs',
    appId: '1:497925542217:ios:a7ab3a7eb5ad4ca5200a98',
    messagingSenderId: '497925542217',
    projectId: 'flutter-ai-au-sample',
    storageBucket: 'flutter-ai-au-sample.firebasestorage.app',
    iosBundleId: 'com.example.flutterAiSample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcFK4n8LKAKw8ZVSABN0zqUJkPehCOR70',
    appId: '1:497925542217:web:b27d9d4a46ebb61c200a98',
    messagingSenderId: '497925542217',
    projectId: 'flutter-ai-au-sample',
    authDomain: 'flutter-ai-au-sample.firebaseapp.com',
    storageBucket: 'flutter-ai-au-sample.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcFK4n8LKAKw8ZVSABN0zqUJkPehCOR70',
    appId: '1:497925542217:web:8a773b6623dab7c2200a98',
    messagingSenderId: '497925542217',
    projectId: 'flutter-ai-au-sample',
    authDomain: 'flutter-ai-au-sample.firebaseapp.com',
    storageBucket: 'flutter-ai-au-sample.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAl9HZV3RgWfAh8Oe9Cg1CCG2WSKt93xs',
    appId: '1:497925542217:ios:a7ab3a7eb5ad4ca5200a98',
    messagingSenderId: '497925542217',
    projectId: 'flutter-ai-au-sample',
    storageBucket: 'flutter-ai-au-sample.firebasestorage.app',
    iosBundleId: 'com.example.flutterAiSample',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUgsOY5yYjMjjiBbOFY-HAUfVaM_FoEUQ',
    appId: '1:497925542217:android:221a9d7269e5212b200a98',
    messagingSenderId: '497925542217',
    projectId: 'flutter-ai-au-sample',
    storageBucket: 'flutter-ai-au-sample.firebasestorage.app',
  );

}