// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZvhNmoFV9vcguWvLi-qRQMLVZs25CsoI',
    appId: '1:560145882418:web:ac08c81fd6518b9ce74b2b',
    messagingSenderId: '560145882418',
    projectId: 'safe-bet-54e87',
    authDomain: 'safe-bet-54e87.firebaseapp.com',
    storageBucket: 'safe-bet-54e87.firebasestorage.app',
    measurementId: 'G-W90T7GR46H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_1ZzZ-nVFh96Uenlpuy9dZrfZIPGOBBY',
    appId: '1:560145882418:android:33518b9f5d83e2b2e74b2b',
    messagingSenderId: '560145882418',
    projectId: 'safe-bet-54e87',
    storageBucket: 'safe-bet-54e87.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALMNR3U0z6A8aaXc1UYigy6bINGeIz7A0',
    appId: '1:560145882418:ios:7785570a41572f28e74b2b',
    messagingSenderId: '560145882418',
    projectId: 'safe-bet-54e87',
    storageBucket: 'safe-bet-54e87.firebasestorage.app',
    iosBundleId: 'com.example.safeBetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALMNR3U0z6A8aaXc1UYigy6bINGeIz7A0',
    appId: '1:560145882418:ios:7785570a41572f28e74b2b',
    messagingSenderId: '560145882418',
    projectId: 'safe-bet-54e87',
    storageBucket: 'safe-bet-54e87.firebasestorage.app',
    iosBundleId: 'com.example.safeBetApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZvhNmoFV9vcguWvLi-qRQMLVZs25CsoI',
    appId: '1:560145882418:web:5522036b0a14d03de74b2b',
    messagingSenderId: '560145882418',
    projectId: 'safe-bet-54e87',
    authDomain: 'safe-bet-54e87.firebaseapp.com',
    storageBucket: 'safe-bet-54e87.firebasestorage.app',
    measurementId: 'G-95NKMX8MK8',
  );
}
